### ISSUE TITLE
pyproject.toml needs fields re-ordered to work

### ISSUE THREAD

**Issue by GillySpace27** [STBadman/ParkerSolarWind#3]
I was able to get the package to install, but I had to rearrange some of the fields in the"pyproject.toml" file. The following snippet should work, I just don't know the best way to contribute to this project. All that I really changed was moving things out of [project.optional-dependencies] and into [project]. Specifically, "authors," "requires-python," "description," " and "readme."

```
[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "parkersolarwind"
version = "0.1.0"
authors = [
  {name = "Sam Badman", email = "me@example.com"}
]
dependencies = [
	"astropy >= 5.0",
	"matplotlib >= 3.6",
	"numpy >= 1.21",
	"scipy >= 1.8",
]
requires-python = " >= 3.8"
description ="Python code to produce Parker solar wind solutions (isothermal, polytropic and isotherm-polytrope 2-layer)"
readme = "README.md"

[project.optional-dependencies]
tests = [
  "pytest",
  "pytest-cov"
]
docs = [
  "sphinx",
  "pydata_sphinx_theme"
]
lint = [
  "black",
  "flake8"
]

```

**Comment by STBadman** [comment]
Thanks so much! I am trying to package this for pypi for the first time and learning as I go.

I wanted to add in pytest as an optional dependency and looks like I broke @svank 's original .toml version. 

In any case, I'm very happy to have contributions. Feel free to fork and submit a PR with this new .toml file, or if you don't have time let me know and I'll do a push with your snippet.

**Comment by GillySpace27** [comment]
I'll do the fork thing, that sounds fun and I haven't done it before. :)


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by STBadman** [comment]
Resolved by PR https://github.com/STBadman/ParkerSolarWind/pull/4
